name: Build the Greenbone Documentation

on:
  pull_request:
    branches: [ main ]

jobs:
  build-docs:
    name: Build Documentation
    runs-on: 'ubuntu-latest'
    strategy:
        matrix:
          python-version:
            - 3.8
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry and dependencies
        uses: greenbone/actions/poetry@v1
      - name: Build docs
        run: poetry run sphinx-build -W --keep-going -b html src _build
